import EventList from "@/components/Events/EventList";
import Title from "@/components/UI/Title";
import { getFeaturedEvents } from "@/db";
import Head from "next/head";

export default function Home() {

  const featuredEvents = getFeaturedEvents();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Title>Featured Events</Title>
        <EventList events={featuredEvents} />
      </div>
    </>
  );
}

export const getServerSideProps = (context) => {
  const { params, req, res } = context;
  
  return {
    props: {

    }
  };
}