import EventList from "@/components/Events/EventList";
import Title from "@/components/UI/Title";
import { getFeaturedEvents } from "@/helpers/api-utils";
import Head from "next/head";

export default function Home({ events }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Title>Featured Events</Title>
        <EventList events={events} />
      </div>
    </>
  );
}

export const getStaticProps = async (context) => {
  const { params, req, res } = context;
  const featuredEvents = await getFeaturedEvents();
  return {
    props: {
      events: featuredEvents,
    },
    revalidate: 60 * 30,
  };
}